import { NgModule } from '@angular/core';
import { NZ_ICONS, NzIconModule } from 'ng-zorro-antd/icon';

import {
  AreaChartOutline,
  CarFill,
  DashboardOutline,
  FormOutline,
  GiftFill,
  HomeFill,
  IdcardFill,
  ImportOutline,
  LockOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  PlusOutline,
  RedoOutline,
  SettingFill,
  UserOutline,
  WarningFill,
  PlusSquareOutline,
  MinusSquareOutline,
  MinusOutline,
  PictureFill,
  LogoutOutline,
  MoneyCollectFill,
  ScheduleFill,
  FilterOutline,
  PercentageOutline,
  PayCircleFill,
  PictureTwoTone,
  DownloadOutline,
  MoreOutline,
  FileExcelOutline,
  SyncOutline,
  CreditCardFill,
  ReloadOutline,
  FieldTimeOutline,
  PoweroffOutline,
  FileExcelFill,
  LoginOutline,
  SettingOutline,
  AuditOutline,
  UsergroupAddOutline,
  ProjectFill,
  ArrowRightOutline,
  AppstoreOutline,
  RightOutline,
  LeftOutline,
  SendOutline,
} from '@ant-design/icons-angular/icons';
import {
  FaIconLibrary,
  FontAwesomeModule,
} from '@fortawesome/angular-fontawesome';
import { fas } from '@fortawesome/free-solid-svg-icons';

const icons = [
  MenuFoldOutline,
  MenuUnfoldOutline,
  DashboardOutline,
  FormOutline,
  AreaChartOutline,
  UserOutline,
  CarFill,
  GiftFill,
  SettingFill,
  WarningFill,
  IdcardFill,
  PlusOutline,
  RedoOutline,
  HomeFill,
  ImportOutline,
  LockOutline,
  PlusSquareOutline,
  MinusSquareOutline,
  MinusOutline,
  PictureFill,
  LogoutOutline,
  MoneyCollectFill,
  ScheduleFill,
  FilterOutline,
  PercentageOutline,
  PayCircleFill,
  PictureTwoTone,
  DownloadOutline,
  MoreOutline,
  FileExcelOutline,
  SyncOutline,
  CreditCardFill,
  CarFill,
  ReloadOutline,
  FieldTimeOutline,
  PoweroffOutline,
  FileExcelFill,
  LoginOutline,
  SettingOutline,
  AuditOutline,
  UsergroupAddOutline,
  ProjectFill,
  ArrowRightOutline,
  AppstoreOutline,
  RightOutline,
  LeftOutline,
  SendOutline,
];

@NgModule({
  imports: [NzIconModule, FontAwesomeModule],
  exports: [NzIconModule, FontAwesomeModule],
  providers: [{ provide: NZ_ICONS, useValue: icons }],
})
export class IconsProviderModule {
  constructor(library: FaIconLibrary) {
    library.addIconPacks(fas);
  }
}
